import {
  Download,
  ArrowRight,
  Linkedin,
  Github,
  Building2,
  Calendar,
  StarIcon,
  BadgeDollarSign,
  Bike,
  BookHeart,
  BriefcaseBusiness,
  ClockIcon,
  Cpu,
  FlaskRound,
  HeartPulse,
  Scale,
  ExternalLink,
  ArrowLeft,
} from "lucide-react";

export const Icons = {
  download: Download,
  arrowRight: ArrowRight,
  linkedin: Linkedin,
  github: Github,
  building2: Building2,
  calendar: Calendar,
  starIcon: StarIcon,
  badgeDollarSign: BadgeDollarSign,
  bike: Bike,
  bookHeart: BookHeart,
  briefcaseBusiness: BriefcaseBusiness,
  clockIcon: ClockIcon,
  cpu: Cpu,
  flaskRound: FlaskRound,
  heartPulse: HeartPulse,
  scale: Scale,
  externalLink: ExternalLink,
  arrowLeft: ArrowLeft,
};
