CREATE TYPE "status" AS ENUM (
  'draft',
  'published',
  'archived'
);

CREATE TYPE "visibility" AS ENUM (
  'public',
  'private'
);

CREATE TYPE "skill_level" AS ENUM (
  'beginner',
  'intermediate',
  'advanced',
  'expert'
);

CREATE TYPE "skill_category" AS ENUM (
  'frontend',
  'backend',
  'devops',
  'data',
  'soft',
  'other'
);

CREATE TYPE "media_owner_type" AS ENUM (
  'project',
  'experience',
  'skill'
);

CREATE TYPE "media_kind" AS ENUM (
  'cover',
  'gallery',
  'icon',
  'other'
);

CREATE TYPE "employment_type" AS ENUM (
  'full_time',
  'part_time',
  'freelance',
  'contract',
  'internship',
  'temporary'
);

CREATE TABLE "skills" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text NOT NULL,
  "slug" text UNIQUE NOT NULL,
  "level" skill_level,
  "category" skill_category,
  "description" text,
  "order_rank" int NOT NULL DEFAULT 0,
  "status" status NOT NULL DEFAULT 'draft',
  "meta" jsonb,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now()),
  "deleted_at" timestamptz
);

CREATE TABLE "projects" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" text NOT NULL,
  "slug" text UNIQUE NOT NULL,
  "summary" text,
  "description" text,
  "start_date" date,
  "end_date" date,
  "repo_url" text,
  "live_url" text,
  "visibility" visibility NOT NULL DEFAULT 'public',
  "status" status NOT NULL DEFAULT 'draft',
  "order_rank" int NOT NULL DEFAULT 0,
  "meta" jsonb,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now()),
  "deleted_at" timestamptz
);

CREATE TABLE "experiences" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "company_name" text NOT NULL,
  "role_title" text NOT NULL,
  "location" text,
  "employment_type" employment_type,
  "start_date" date NOT NULL,
  "end_date" date,
  "summary" text,
  "achievements" jsonb,
  "status" status NOT NULL DEFAULT 'draft',
  "order_rank" int NOT NULL DEFAULT 0,
  "meta" jsonb,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now()),
  "deleted_at" timestamptz
);

CREATE TABLE "project_skills" (
  "project_id" bigint NOT NULL,
  "skill_id" bigint NOT NULL,
  "weight" int NOT NULL DEFAULT 1,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  PRIMARY KEY ("project_id", "skill_id")
);

CREATE TABLE "experience_projects" (
  "experience_id" bigint NOT NULL,
  "project_id" bigint NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  PRIMARY KEY ("experience_id", "project_id")
);

CREATE TABLE "media_assets" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "owner_type" media_owner_type NOT NULL,
  "owner_id" bigint NOT NULL,
  "kind" media_kind NOT NULL DEFAULT 'cover',
  "storage_path" text NOT NULL,
  "mime" text,
  "width" int,
  "height" int,
  "size_bytes" bigint,
  "alt" text,
  "caption" text,
  "credit" text,
  "focal_x" float,
  "focal_y" float,
  "blurhash" text,
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE INDEX "idx_skills_status" ON "skills" ("status");

CREATE INDEX "idx_skills_order" ON "skills" ("order_rank");

CREATE INDEX "idx_projects_status" ON "projects" ("status");

CREATE INDEX "idx_projects_visibility_status" ON "projects" ("visibility", "status");

CREATE INDEX "idx_projects_order" ON "projects" ("order_rank");

CREATE INDEX "idx_experiences_status" ON "experiences" ("status");

CREATE INDEX "idx_experiences_order" ON "experiences" ("order_rank");

CREATE INDEX ON "project_skills" ("skill_id");

CREATE INDEX ON "project_skills" ("project_id");

CREATE INDEX ON "experience_projects" ("project_id");

CREATE INDEX ON "experience_projects" ("experience_id");

CREATE INDEX "idx_media_owner" ON "media_assets" ("owner_type", "owner_id");

CREATE INDEX ON "media_assets" ("kind");

CREATE UNIQUE INDEX "uq_media_single_cover" ON "media_assets" ("owner_type", "owner_id", "kind");

COMMENT ON TABLE "projects" IS 'Progetti/Case studies. Slug unico. Pubblico/privato + stato per workflow.';

COMMENT ON TABLE "media_assets" IS 'I file vivono nello storage (Supabase Storage/CDN). Qui solo metadati e collegamenti.';

ALTER TABLE "project_skills" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("id");

ALTER TABLE "project_skills" ADD FOREIGN KEY ("skill_id") REFERENCES "skills" ("id");

ALTER TABLE "experience_projects" ADD FOREIGN KEY ("experience_id") REFERENCES "experiences" ("id");

ALTER TABLE "experience_projects" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("id");
